##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 18 21:02:29 /etc/localtime 2001
#    copyright            : (C) 2000 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################



DATADIR   = cars/porsche-gt3rs

DATA      = porsche-gt3rs.xml porsche-gt3rs.ac porsche-gt3rs.rgb tex-wheel.rgb porsche-gt3rs-src.ac
# texmapper.xml porsche-gt3rs-base.ac

data-cars-gt_PKGFILES	= $(DATA)

data-cars-gt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


