##############################################################################
#
#    file                 : Makefile
#    created              : Sun Apr 30 15:45:24 CEST 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/dirt/dirt-3

DATA      = dirt-3.xml background.png background2.png dirt-3.ac dirt-3-relief.ac dirt-3.png

base-tracks_PKGFILES	= $(DATA)

base-tracks_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


