##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mar 18 23:03:41 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = cars/cg-nascar-rwd

DATA      = cg-nascar-rwd.xml cg-nascar-rwd.ac cg-nascar-rwd-lod1.ac cg-nascar-rwd.rgb tex-wheel.rgb

data-cars-gt_PKGFILES= $(DATA)

data-cars-gt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


