##############################################################################
#
#    file                 : Makefile
#    created              : Fri Dec 23 17:35:18 CET 2011
#    copyright            : (C) 2011 Bernhard Wymann                         
#    email                : berniw@bluewin.ch   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

DATADIR   	= data/music

DATA      	= $(shell find *.ogg -maxdepth 0 -type f)

data_PKGFILES	= $(DATA)

data_PKGDIR	= $(DATADIR)


include ${MAKE_DEFAULT}


