##############################################################################
#
#    file                 : Makefile
#    created              : Tue Sep 25 02:21:46 CET 2012
#    copyright            : (C) 2012 by Bernhard Wymann                         
#    email                : berniw@bluewin.ch   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/hidden-valley

DATA      = 01.png 02.png ALAUBM.png armcogrille_tree_n.png armco-left.png armco.png armco-right.png \
	background.png BLBDBK.png BRIDGEAD.png BTOWB.png BUS.png CAMPER01.png CAMPER02.png CAMPER3.png \
	CAMPER41.png CAMPER4.png CAR01.png CAR02.png CAR05.png CAR06.png CAR07.png CAR08.png carpark.png \
	CMNTA.png CMNTBB.png CMNTB.png concrete-wall1.png CONCRETW.png CONCSH01.png CONCSH02.png \
	CONCTP.png dekk01.png DIST01.png DIST02.png DIST03.png DIST04.png FNCEB.png GBtree_n.png \
	GCtree_n.png GDtree_n.png GEtree_n.png GFtree_n.png GGtree.png GRASS.png grass-underlay.png \
	GRtree_n.png GSPAtree.png GSSOLID.png GSUNDER.png hidden-valley.acc \
	hidden-valley.png hidden-valley.xml LAMAOP.png LOGOBRDG.png LOGOCAMP.png LOGODD.png LOGOFSTN.png \
	LOGOGFLG.png LOGOHYMIE.png LOGOITAL.png LOGOJEDI.png LOGOSIEGER.png LOGOSOFTENG.png LOGOUSR.png \
	LOGOWR.png MASE01.png MASE02.png OBJA09.png OBJA11.png OBJA13.png OBJA24_arbor_n.png \
	PALAZA01.png PALAZA02.png PALAZA03.png PALAZA04.png PALAZA05.png PALAZA06.png PALAZA07.png \
	PALAZA09.png PALAZA10.png PALAZA11.png PALAZA12.png PALAZA13.png PALAZA16.png PALAZA17.png \
	PALAZA22.png PALAZA23_arbor_n.png PALAZA24.png PDKKA13b.png PDKKA13.png PDKKA14.png PDtree_n.png \
	PITWB.png POLEA.png POLLOL.png RA4BRIG5.png raceline-clean.png raceline.png raceline-trans.png \
	readme.txt REF.png rk_tree_2_n.png ROAD05.png roadgras.png ROAD_LINE_n.png ROAD_n.png \
	ROAD_PIT_ENTRYEXIT_n.png ROAD_PIT_ENTRYEXIT_SIDE_n.png ROAD_PIT_n.png ROAD_PIT.png ROADPL_n.png \
	roadsand.png RSA02.png ruudskog_arbor.png SAND02.png SEMA02.png shadow2.rgb shadow.png \
	shadow-terrain.png STAIRSD.png STAIRS.png TENTD.png TENTH.png TIME1A.png TIME1B.png TIME2B.png \
	tirewall-left.png tirewall.png tirewall-right.png TOPCROWD.png trans-roadsandgrass.png \
	trans-sandgrass.png tr-barrier-tree.png tree-fir_n.png treeline_n.png tree-pine1_n.png \
	TreeRNS3.png TreeRNS4.png TreeRNS5.png treeUGLIES01_n.png treeUGLIES02_n.png TRIBA08.png \
	TRIBA09_arbor_n.png TRIBA11.png TRIBB01.png TRIBB02.png TRIBB03.png TRKJUMA.png TRKJUMB.png \
	TRKJUMC.png TRKJUM.png WHEELS6.png ZBRID.png ZPIT3.png ZPIT.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)


include ${MAKE_DEFAULT}


