@echo off
echo Checking directories ...


call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\interfaces\graphic.h .\export\include\graphic.h
copy .\src\interfaces\raceman.h .\export\include\raceman.h
copy .\src\interfaces\robot.h .\export\include\robot.h
copy .\src\interfaces\simu.h .\export\include\simu.h
copy .\src\interfaces\track.h .\export\include\track.h
copy .\src\interfaces\car.h .\export\include\car.h
copy .\src\interfaces\ttypes.h .\export\include\ttypes.h
copy .\src\interfaces\telemetry.h .\export\include\telemetry.h
copy .\src\interfaces\practicectrl.h .\export\include\practicectrl.h
copy .\src\interfaces\playerpref.h .\export\include\playerpref.h

call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\libs\txml\xml.h .\export\include\xml.h
copy .\src\libs\txml\xmlparse.h .\export\include\xmlparse.h

call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\libs\tgf\tgf.h .\export\include\tgf.h
copy .\src\libs\tgf\os.h .\export\include\os.h

call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\libs\torcs\torcs.h .\export\include\torcs.h

call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\libs\racemantools\racemantools.h .\export\include\racemantools.h

call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\libs\robottools\robottools.h .\export\include\robottools.h

call .\create_dir .\export
call .\create_dir .\export\include
copy .\src\windows\osspec.h .\export\include\osspec.h

call .\create_dir .\export
call .\create_dir .\export\include
call .\create_dir .\export\include\3D
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Basic.h .\export\include\3D\Basic.h
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Matrix.h .\export\include\3D\Matrix.h
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Point.h .\export\include\3D\Point.h
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Quaternion.h .\export\include\3D\Quaternion.h
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Tuple3.h .\export\include\3D\Tuple3.h
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Tuple4.h .\export\include\3D\Tuple4.h
copy .\src\modules\simu\simuv2\SOLID-2.0\include\3D\Vector.h .\export\include\3D\Vector.h

call .\create_dir .\export
call .\create_dir .\export\include
call .\create_dir .\export\include\SOLID
copy .\src\modules\simu\simuv2\SOLID-2.0\include\SOLID\solid.h .\export\include\SOLID\solid.h

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\free\free.xml \home\torcs\essai\games\torcs\categories\free.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\offroad-r-a\offroad-r-a.xml \home\torcs\essai\games\torcs\categories\offroad-r-a.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\torcs-f-a\torcs-f-a.xml \home\torcs\essai\games\torcs\categories\torcs-f-a.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\torcs-f-b\torcs-f-b.xml \home\torcs\essai\games\torcs\categories\torcs-f-b.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\torcs-r-a\torcs-r-a.xml \home\torcs\essai\games\torcs\categories\torcs-r-a.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\torcs-r-b\torcs-r-b.xml \home\torcs\essai\games\torcs\categories\torcs-r-b.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\categories
copy .\data\cars\categories\torcs-r-c\torcs-r-c.xml \home\torcs\essai\games\torcs\categories\torcs-r-c.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\acura-nsx-sz
copy .\data\cars\models\acura-nsx-sz\acura-nsx-sz.xml \home\torcs\essai\games\torcs\cars\acura-nsx-sz\acura-nsx-sz.xml
copy .\data\cars\models\acura-nsx-sz\acura-nsx-sz.ac \home\torcs\essai\games\torcs\cars\acura-nsx-sz\acura-nsx-sz.ac
copy .\data\cars\models\acura-nsx-sz\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\acura-nsx-sz\tex-wheel.rgb
copy .\data\cars\models\acura-nsx-sz\acura-nsx-sz.rgb \home\torcs\essai\games\torcs\cars\acura-nsx-sz\acura-nsx-sz.rgb
copy .\data\cars\models\acura-nsx-sz\acura-nsx-sz-base.ac \home\torcs\essai\games\torcs\cars\acura-nsx-sz\acura-nsx-sz-base.ac
copy .\data\cars\models\acura-nsx-sz\texmapper.xml \home\torcs\essai\games\torcs\cars\acura-nsx-sz\texmapper.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\buggy
copy .\data\cars\models\buggy\buggy.xml \home\torcs\essai\games\torcs\cars\buggy\buggy.xml
copy .\data\cars\models\buggy\buggy.ac \home\torcs\essai\games\torcs\cars\buggy\buggy.ac
copy .\data\cars\models\buggy\buggy.rgb \home\torcs\essai\games\torcs\cars\buggy\buggy.rgb
copy .\data\cars\models\buggy\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\buggy\tex-wheel.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\cg-nascar-fwd
copy .\data\cars\models\cg-nascar-fwd\cg-nascar-fwd.xml \home\torcs\essai\games\torcs\cars\cg-nascar-fwd\cg-nascar-fwd.xml
copy .\data\cars\models\cg-nascar-fwd\cg-nascar-fwd.ac \home\torcs\essai\games\torcs\cars\cg-nascar-fwd\cg-nascar-fwd.ac
copy .\data\cars\models\cg-nascar-fwd\cg-nascar-fwd.rgb \home\torcs\essai\games\torcs\cars\cg-nascar-fwd\cg-nascar-fwd.rgb
copy .\data\cars\models\cg-nascar-fwd\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\cg-nascar-fwd\tex-wheel.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\cg-nascar-rwd
copy .\data\cars\models\cg-nascar-rwd\cg-nascar-rwd.xml \home\torcs\essai\games\torcs\cars\cg-nascar-rwd\cg-nascar-rwd.xml
copy .\data\cars\models\cg-nascar-rwd\cg-nascar-rwd.ac \home\torcs\essai\games\torcs\cars\cg-nascar-rwd\cg-nascar-rwd.ac
copy .\data\cars\models\cg-nascar-rwd\cg-nascar-rwd.rgb \home\torcs\essai\games\torcs\cars\cg-nascar-rwd\cg-nascar-rwd.rgb
copy .\data\cars\models\cg-nascar-rwd\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\cg-nascar-rwd\tex-wheel.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\lotus-gt1
copy .\data\cars\models\lotus-gt1\lotus-gt1.xml \home\torcs\essai\games\torcs\cars\lotus-gt1\lotus-gt1.xml
copy .\data\cars\models\lotus-gt1\lotus-gt1.ac \home\torcs\essai\games\torcs\cars\lotus-gt1\lotus-gt1.ac
copy .\data\cars\models\lotus-gt1\lotus-gt1-base.ac \home\torcs\essai\games\torcs\cars\lotus-gt1\lotus-gt1-base.ac
copy .\data\cars\models\lotus-gt1\texmapper.xml \home\torcs\essai\games\torcs\cars\lotus-gt1\texmapper.xml
copy .\data\cars\models\lotus-gt1\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\lotus-gt1\tex-wheel.rgb
copy .\data\cars\models\lotus-gt1\lotus-gt1.rgb \home\torcs\essai\games\torcs\cars\lotus-gt1\lotus-gt1.rgb
copy .\data\cars\models\lotus-gt1\lotus-gt1-512.rgb \home\torcs\essai\games\torcs\cars\lotus-gt1\lotus-gt1-512.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\mclaren-f1
copy .\data\cars\models\mclaren-f1\mclaren-f1.xml \home\torcs\essai\games\torcs\cars\mclaren-f1\mclaren-f1.xml
copy .\data\cars\models\mclaren-f1\mclaren-f1.ac \home\torcs\essai\games\torcs\cars\mclaren-f1\mclaren-f1.ac
copy .\data\cars\models\mclaren-f1\mclaren-f1-base.ac \home\torcs\essai\games\torcs\cars\mclaren-f1\mclaren-f1-base.ac
copy .\data\cars\models\mclaren-f1\texmapper.xml \home\torcs\essai\games\torcs\cars\mclaren-f1\texmapper.xml
copy .\data\cars\models\mclaren-f1\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\mclaren-f1\tex-wheel.rgb
copy .\data\cars\models\mclaren-f1\mclaren-f1.rgb \home\torcs\essai\games\torcs\cars\mclaren-f1\mclaren-f1.rgb
copy .\data\cars\models\mclaren-f1\mclaren-f1-512.rgb \home\torcs\essai\games\torcs\cars\mclaren-f1\mclaren-f1-512.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\p406
copy .\data\cars\models\p406\p406.xml \home\torcs\essai\games\torcs\cars\p406\p406.xml
copy .\data\cars\models\p406\texmapper.xml \home\torcs\essai\games\torcs\cars\p406\texmapper.xml
copy .\data\cars\models\p406\p406.ac \home\torcs\essai\games\torcs\cars\p406\p406.ac
copy .\data\cars\models\p406\p406-base.ac \home\torcs\essai\games\torcs\cars\p406\p406-base.ac
copy .\data\cars\models\p406\p406-512.rgb \home\torcs\essai\games\torcs\cars\p406\p406-512.rgb
copy .\data\cars\models\p406\p406.rgb \home\torcs\essai\games\torcs\cars\p406\p406.rgb
copy .\data\cars\models\p406\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\p406\tex-wheel.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\torcs
copy .\data\cars\models\torcs\torcs.xml \home\torcs\essai\games\torcs\cars\torcs\torcs.xml
copy .\data\cars\models\torcs\torcs.ac \home\torcs\essai\games\torcs\cars\torcs\torcs.ac
copy .\data\cars\models\torcs\torcs.rgb \home\torcs\essai\games\torcs\cars\torcs\torcs.rgb
copy .\data\cars\models\torcs\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\torcs\tex-wheel.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\cars
call .\create_dir .\home\torcs\essai\games\torcs\cars\viper-gts-r
copy .\data\cars\models\viper-gts-r\viper-gts-r.xml \home\torcs\essai\games\torcs\cars\viper-gts-r\viper-gts-r.xml
copy .\data\cars\models\viper-gts-r\tex-wheel.rgb \home\torcs\essai\games\torcs\cars\viper-gts-r\tex-wheel.rgb
copy .\data\cars\models\viper-gts-r\viper-gts-r.rgb \home\torcs\essai\games\torcs\cars\viper-gts-r\viper-gts-r.rgb
copy .\data\cars\models\viper-gts-r\viper-gts-r.ac \home\torcs\essai\games\torcs\cars\viper-gts-r\viper-gts-r.ac
copy .\data\cars\models\viper-gts-r\viper-gts-r-512.rgb \home\torcs\essai\games\torcs\cars\viper-gts-r\viper-gts-r-512.rgb
copy .\data\cars\models\viper-gts-r\viper-gts-r-base.ac \home\torcs\essai\games\torcs\cars\viper-gts-r\viper-gts-r-base.ac
copy .\data\cars\models\viper-gts-r\texmapper.xml \home\torcs\essai\games\torcs\cars\viper-gts-r\texmapper.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\data
call .\create_dir .\home\torcs\essai\games\torcs\data\fonts
copy .\data\data\fonts\b5.glf \home\torcs\essai\games\torcs\data\fonts\b5.glf
copy .\data\data\fonts\b6.glf \home\torcs\essai\games\torcs\data\fonts\b6.glf
copy .\data\data\fonts\b7.glf \home\torcs\essai\games\torcs\data\fonts\b7.glf
copy .\data\data\fonts\digital.glf \home\torcs\essai\games\torcs\data\fonts\digital.glf
copy .\data\data\fonts\fragile.glf \home\torcs\essai\games\torcs\data\fonts\fragile.glf
copy .\data\data\fonts\Makefile \home\torcs\essai\games\torcs\data\fonts\Makefile

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\data
call .\create_dir .\home\torcs\essai\games\torcs\data\img
copy .\data\data\img\arrow-down.png \home\torcs\essai\games\torcs\data\img\arrow-down.png
copy .\data\data\img\arrow-down-pushed.png \home\torcs\essai\games\torcs\data\img\arrow-down-pushed.png
copy .\data\data\img\arrow-left.png \home\torcs\essai\games\torcs\data\img\arrow-left.png
copy .\data\data\img\arrow-left-pushed.png \home\torcs\essai\games\torcs\data\img\arrow-left-pushed.png
copy .\data\data\img\arrow-right.png \home\torcs\essai\games\torcs\data\img\arrow-right.png
copy .\data\data\img\arrow-right-pushed.png \home\torcs\essai\games\torcs\data\img\arrow-right-pushed.png
copy .\data\data\img\arrow-up.png \home\torcs\essai\games\torcs\data\img\arrow-up.png
copy .\data\data\img\arrow-up-pushed.png \home\torcs\essai\games\torcs\data\img\arrow-up-pushed.png
copy .\data\data\img\env.png \home\torcs\essai\games\torcs\data\img\env.png
copy .\data\data\img\ruler.png \home\torcs\essai\games\torcs\data\img\ruler.png
copy .\data\data\img\ruler-pushed.png \home\torcs\essai\games\torcs\data\img\ruler-pushed.png
copy .\data\data\img\splash-free1.png \home\torcs\essai\games\torcs\data\img\splash-free1.png
copy .\data\data\img\splash-free2.png \home\torcs\essai\games\torcs\data\img\splash-free2.png
copy .\data\data\img\splash-free3.png \home\torcs\essai\games\torcs\data\img\splash-free3.png
copy .\data\data\img\splash-free4.png \home\torcs\essai\games\torcs\data\img\splash-free4.png
copy .\data\data\img\splash-free5.png \home\torcs\essai\games\torcs\data\img\splash-free5.png
copy .\data\data\img\splash-free7.png \home\torcs\essai\games\torcs\data\img\splash-free7.png
copy .\data\data\img\splash-free.png \home\torcs\essai\games\torcs\data\img\splash-free.png
copy .\data\data\img\splash-graphic.png \home\torcs\essai\games\torcs\data\img\splash-graphic.png
copy .\data\data\img\splash-joycal.png \home\torcs\essai\games\torcs\data\img\splash-joycal.png
copy .\data\data\img\splash-joyconf.png \home\torcs\essai\games\torcs\data\img\splash-joyconf.png
copy .\data\data\img\splash-main.png \home\torcs\essai\games\torcs\data\img\splash-main.png
copy .\data\data\img\splash-options.png \home\torcs\essai\games\torcs\data\img\splash-options.png
copy .\data\data\img\splash.png \home\torcs\essai\games\torcs\data\img\splash.png
copy .\data\data\img\splash-practice.png \home\torcs\essai\games\torcs\data\img\splash-practice.png
copy .\data\data\img\splash-prsess.png \home\torcs\essai\games\torcs\data\img\splash-prsess.png
copy .\data\data\img\splash-qrdrv.png \home\torcs\essai\games\torcs\data\img\splash-qrdrv.png
copy .\data\data\img\splash-qrloading.png \home\torcs\essai\games\torcs\data\img\splash-qrloading.png
copy .\data\data\img\splash-qr.png \home\torcs\essai\games\torcs\data\img\splash-qr.png
copy .\data\data\img\splash-qrtrk.png \home\torcs\essai\games\torcs\data\img\splash-qrtrk.png
copy .\data\data\img\splash-quit.png \home\torcs\essai\games\torcs\data\img\splash-quit.png
copy .\data\data\img\splash-result.png \home\torcs\essai\games\torcs\data\img\splash-result.png

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\menu
copy .\data\data\menu\entry.xml \home\torcs\essai\games\torcs\menu\entry.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\data
call .\create_dir .\home\torcs\essai\games\torcs\data\objects
copy .\data\data\objects\stand-inter.ac \home\torcs\essai\games\torcs\data\objects\stand-inter.ac
copy .\data\data\objects\stand-main.ac \home\torcs\essai\games\torcs\data\objects\stand-main.ac
copy .\data\data\objects\stand-wall.ac \home\torcs\essai\games\torcs\data\objects\stand-wall.ac
copy .\data\data\objects\tree1.ac \home\torcs\essai\games\torcs\data\objects\tree1.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\data
call .\create_dir .\home\torcs\essai\games\torcs\data\sound
copy .\data\data\sound\crash1.wav \home\torcs\essai\games\torcs\data\sound\crash1.wav
copy .\data\data\sound\crash2.wav \home\torcs\essai\games\torcs\data\sound\crash2.wav
copy .\data\data\sound\crash3.wav \home\torcs\essai\games\torcs\data\sound\crash3.wav
copy .\data\data\sound\crash4.wav \home\torcs\essai\games\torcs\data\sound\crash4.wav
copy .\data\data\sound\crash5.wav \home\torcs\essai\games\torcs\data\sound\crash5.wav
copy .\data\data\sound\crash6.wav \home\torcs\essai\games\torcs\data\sound\crash6.wav
copy .\data\data\sound\engine-1.wav \home\torcs\essai\games\torcs\data\sound\engine-1.wav
copy .\data\data\sound\skid.wav \home\torcs\essai\games\torcs\data\sound\skid.wav

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\data
call .\create_dir .\home\torcs\essai\games\torcs\data\textures
copy .\data\data\textures\background.png \home\torcs\essai\games\torcs\data\textures\background.png
copy .\data\data\textures\logo.png \home\torcs\essai\games\torcs\data\textures\logo.png
copy .\data\data\textures\pylon1.png \home\torcs\essai\games\torcs\data\textures\pylon1.png
copy .\data\data\textures\pylon2.png \home\torcs\essai\games\torcs\data\textures\pylon2.png
copy .\data\data\textures\pylon3.png \home\torcs\essai\games\torcs\data\textures\pylon3.png
copy .\data\data\textures\tr-asphalt-both.png \home\torcs\essai\games\torcs\data\textures\tr-asphalt-both.png
copy .\data\data\textures\tr-asphalt-left.png \home\torcs\essai\games\torcs\data\textures\tr-asphalt-left.png
copy .\data\data\textures\tr-asphalt-l.png \home\torcs\essai\games\torcs\data\textures\tr-asphalt-l.png
copy .\data\data\textures\tr-asphalt.png \home\torcs\essai\games\torcs\data\textures\tr-asphalt.png
copy .\data\data\textures\tr-asphalt-p.png \home\torcs\essai\games\torcs\data\textures\tr-asphalt-p.png
copy .\data\data\textures\tr-asphalt-right.png \home\torcs\essai\games\torcs\data\textures\tr-asphalt-right.png
copy .\data\data\textures\tr-barrier.png \home\torcs\essai\games\torcs\data\textures\tr-barrier.png
copy .\data\data\textures\tr-concrete.png \home\torcs\essai\games\torcs\data\textures\tr-concrete.png
copy .\data\data\textures\tr-dirtb.png \home\torcs\essai\games\torcs\data\textures\tr-dirtb.png
copy .\data\data\textures\tr-dirt.png \home\torcs\essai\games\torcs\data\textures\tr-dirt.png
copy .\data\data\textures\tr-grass.png \home\torcs\essai\games\torcs\data\textures\tr-grass.png
copy .\data\data\textures\tr-sand.png \home\torcs\essai\games\torcs\data\textures\tr-sand.png
copy .\data\data\textures\concrete2.rgb \home\torcs\essai\games\torcs\data\textures\concrete2.rgb
copy .\data\data\textures\concrete.rgb \home\torcs\essai\games\torcs\data\textures\concrete.rgb
copy .\data\data\textures\env.rgb \home\torcs\essai\games\torcs\data\textures\env.rgb
copy .\data\data\textures\logo.rgb \home\torcs\essai\games\torcs\data\textures\logo.rgb
copy .\data\data\textures\pit-left.rgb \home\torcs\essai\games\torcs\data\textures\pit-left.rgb
copy .\data\data\textures\pit-right.rgb \home\torcs\essai\games\torcs\data\textures\pit-right.rgb
copy .\data\data\textures\pylon1.rgb \home\torcs\essai\games\torcs\data\textures\pylon1.rgb
copy .\data\data\textures\pylon2.rgb \home\torcs\essai\games\torcs\data\textures\pylon2.rgb
copy .\data\data\textures\pylon3.rgb \home\torcs\essai\games\torcs\data\textures\pylon3.rgb
copy .\data\data\textures\rim1.rgb \home\torcs\essai\games\torcs\data\textures\rim1.rgb
copy .\data\data\textures\rim2.rgb \home\torcs\essai\games\torcs\data\textures\rim2.rgb
copy .\data\data\textures\tr-asphalt-both_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-both_nmm.rgb
copy .\data\data\textures\tr-asphalt-both.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-both.rgb
copy .\data\data\textures\tr-asphalt-left_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-left_nmm.rgb
copy .\data\data\textures\tr-asphalt-left.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-left.rgb
copy .\data\data\textures\tr-asphalt-l_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-l_nmm.rgb
copy .\data\data\textures\tr-asphalt-l.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-l.rgb
copy .\data\data\textures\tr-asphalt_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt_nmm.rgb
copy .\data\data\textures\tr-asphalt-p_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-p_nmm.rgb
copy .\data\data\textures\tr-asphalt-p.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-p.rgb
copy .\data\data\textures\tr-asphalt.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt.rgb
copy .\data\data\textures\tr-asphalt-right_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-right_nmm.rgb
copy .\data\data\textures\tr-asphalt-right.rgb \home\torcs\essai\games\torcs\data\textures\tr-asphalt-right.rgb
copy .\data\data\textures\tr-barrier.rgb \home\torcs\essai\games\torcs\data\textures\tr-barrier.rgb
copy .\data\data\textures\tr-concrete_nmm.rgb \home\torcs\essai\games\torcs\data\textures\tr-concrete_nmm.rgb
copy .\data\data\textures\tr-concrete.rgb \home\torcs\essai\games\torcs\data\textures\tr-concrete.rgb
copy .\data\data\textures\tr-dirtb.rgb \home\torcs\essai\games\torcs\data\textures\tr-dirtb.rgb
copy .\data\data\textures\tr-dirt.rgb \home\torcs\essai\games\torcs\data\textures\tr-dirt.rgb
copy .\data\data\textures\tree1.rgb \home\torcs\essai\games\torcs\data\textures\tree1.rgb
copy .\data\data\textures\tr-grass2.rgb \home\torcs\essai\games\torcs\data\textures\tr-grass2.rgb
copy .\data\data\textures\tr-grass.rgb \home\torcs\essai\games\torcs\data\textures\tr-grass.rgb
copy .\data\data\textures\tr-sand2.rgb \home\torcs\essai\games\torcs\data\textures\tr-sand2.rgb
copy .\data\data\textures\tr-sand.rgb \home\torcs\essai\games\torcs\data\textures\tr-sand.rgb
copy .\data\data\textures\tr-water.rgb \home\torcs\essai\games\torcs\data\textures\tr-water.rgb
copy .\data\data\textures\turn100L.rgb \home\torcs\essai\games\torcs\data\textures\turn100L.rgb
copy .\data\data\textures\turn100R.rgb \home\torcs\essai\games\torcs\data\textures\turn100R.rgb
copy .\data\data\textures\turn150L.rgb \home\torcs\essai\games\torcs\data\textures\turn150L.rgb
copy .\data\data\textures\turn150R.rgb \home\torcs\essai\games\torcs\data\textures\turn150R.rgb
copy .\data\data\textures\turn200L.rgb \home\torcs\essai\games\torcs\data\textures\turn200L.rgb
copy .\data\data\textures\turn200R.rgb \home\torcs\essai\games\torcs\data\textures\turn200R.rgb
copy .\data\data\textures\turn300L.rgb \home\torcs\essai\games\torcs\data\textures\turn300L.rgb
copy .\data\data\textures\turn300R.rgb \home\torcs\essai\games\torcs\data\textures\turn300R.rgb
copy .\data\data\textures\turn50L.rgb \home\torcs\essai\games\torcs\data\textures\turn50L.rgb
copy .\data\data\textures\turn50R.rgb \home\torcs\essai\games\torcs\data\textures\turn50R.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\data
call .\create_dir .\home\torcs\essai\games\torcs\data\tracks
copy .\data\data\tracks\surfaces.xml \home\torcs\essai\games\torcs\data\tracks\surfaces.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\aalborg
copy .\data\tracks\aalborg\aalborg.xml \home\torcs\essai\games\torcs\tracks\aalborg\aalborg.xml
copy .\data\tracks\aalborg\aalborg.ac \home\torcs\essai\games\torcs\tracks\aalborg\aalborg.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\a-speedway
copy .\data\tracks\a-speedway\a-speedway.xml \home\torcs\essai\games\torcs\tracks\a-speedway\a-speedway.xml
copy .\data\tracks\a-speedway\background.png \home\torcs\essai\games\torcs\tracks\a-speedway\background.png
copy .\data\tracks\a-speedway\a-speedway.ac \home\torcs\essai\games\torcs\tracks\a-speedway\a-speedway.ac
copy .\data\tracks\a-speedway\a-speedway-relief.ac \home\torcs\essai\games\torcs\tracks\a-speedway\a-speedway-relief.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\dirt-1
copy .\data\tracks\dirt-1\dirt-1.xml \home\torcs\essai\games\torcs\tracks\dirt-1\dirt-1.xml
copy .\data\tracks\dirt-1\background.png \home\torcs\essai\games\torcs\tracks\dirt-1\background.png
copy .\data\tracks\dirt-1\dirt-1.ac \home\torcs\essai\games\torcs\tracks\dirt-1\dirt-1.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\dirt-2
copy .\data\tracks\dirt-2\dirt-2.xml \home\torcs\essai\games\torcs\tracks\dirt-2\dirt-2.xml
copy .\data\tracks\dirt-2\background.png \home\torcs\essai\games\torcs\tracks\dirt-2\background.png
copy .\data\tracks\dirt-2\dirt-2.ac \home\torcs\essai\games\torcs\tracks\dirt-2\dirt-2.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\dirt-3
copy .\data\tracks\dirt-3\dirt-3.xml \home\torcs\essai\games\torcs\tracks\dirt-3\dirt-3.xml
copy .\data\tracks\dirt-3\background.png \home\torcs\essai\games\torcs\tracks\dirt-3\background.png
copy .\data\tracks\dirt-3\background2.png \home\torcs\essai\games\torcs\tracks\dirt-3\background2.png
copy .\data\tracks\dirt-3\dirt-3.ac \home\torcs\essai\games\torcs\tracks\dirt-3\dirt-3.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\dirt-4
copy .\data\tracks\dirt-4\dirt-4.xml \home\torcs\essai\games\torcs\tracks\dirt-4\dirt-4.xml
copy .\data\tracks\dirt-4\background.png \home\torcs\essai\games\torcs\tracks\dirt-4\background.png
copy .\data\tracks\dirt-4\dirt-4.ac \home\torcs\essai\games\torcs\tracks\dirt-4\dirt-4.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\dirt-5
copy .\data\tracks\dirt-5\dirt-5.xml \home\torcs\essai\games\torcs\tracks\dirt-5\dirt-5.xml
copy .\data\tracks\dirt-5\background.png \home\torcs\essai\games\torcs\tracks\dirt-5\background.png
copy .\data\tracks\dirt-5\dirt-5.ac \home\torcs\essai\games\torcs\tracks\dirt-5\dirt-5.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\dirt-6
copy .\data\tracks\dirt-6\dirt-6.xml \home\torcs\essai\games\torcs\tracks\dirt-6\dirt-6.xml
copy .\data\tracks\dirt-6\background.png \home\torcs\essai\games\torcs\tracks\dirt-6\background.png
copy .\data\tracks\dirt-6\dirt-6.ac \home\torcs\essai\games\torcs\tracks\dirt-6\dirt-6.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\eroad
copy .\data\tracks\eroad\eroad.xml \home\torcs\essai\games\torcs\tracks\eroad\eroad.xml
copy .\data\tracks\eroad\background.png \home\torcs\essai\games\torcs\tracks\eroad\background.png
copy .\data\tracks\eroad\eroad.ac \home\torcs\essai\games\torcs\tracks\eroad\eroad.ac
copy .\data\tracks\eroad\eroad-relief.ac \home\torcs\essai\games\torcs\tracks\eroad\eroad-relief.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\e-track-1
copy .\data\tracks\e-track-1\e-track-1.xml \home\torcs\essai\games\torcs\tracks\e-track-1\e-track-1.xml
copy .\data\tracks\e-track-1\background.png \home\torcs\essai\games\torcs\tracks\e-track-1\background.png
copy .\data\tracks\e-track-1\e-track-1.ac \home\torcs\essai\games\torcs\tracks\e-track-1\e-track-1.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\e-track-2
copy .\data\tracks\e-track-2\e-track-2.xml \home\torcs\essai\games\torcs\tracks\e-track-2\e-track-2.xml
copy .\data\tracks\e-track-2\background.png \home\torcs\essai\games\torcs\tracks\e-track-2\background.png
copy .\data\tracks\e-track-2\e-track-2.ac \home\torcs\essai\games\torcs\tracks\e-track-2\e-track-2.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\e-track-3
copy .\data\tracks\e-track-3\e-track-3.xml \home\torcs\essai\games\torcs\tracks\e-track-3\e-track-3.xml
copy .\data\tracks\e-track-3\background.png \home\torcs\essai\games\torcs\tracks\e-track-3\background.png
copy .\data\tracks\e-track-3\env.rgb \home\torcs\essai\games\torcs\tracks\e-track-3\env.rgb
copy .\data\tracks\e-track-3\e-track-3.ac \home\torcs\essai\games\torcs\tracks\e-track-3\e-track-3.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\e-track-4
copy .\data\tracks\e-track-4\e-track-4.xml \home\torcs\essai\games\torcs\tracks\e-track-4\e-track-4.xml
copy .\data\tracks\e-track-4\background.png \home\torcs\essai\games\torcs\tracks\e-track-4\background.png
copy .\data\tracks\e-track-4\e-track-4.ac \home\torcs\essai\games\torcs\tracks\e-track-4\e-track-4.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\e-track-5
copy .\data\tracks\e-track-5\e-track-5.xml \home\torcs\essai\games\torcs\tracks\e-track-5\e-track-5.xml
copy .\data\tracks\e-track-5\background.png \home\torcs\essai\games\torcs\tracks\e-track-5\background.png
copy .\data\tracks\e-track-5\e-track-5.ac \home\torcs\essai\games\torcs\tracks\e-track-5\e-track-5.ac
copy .\data\tracks\e-track-5\e-track-5-relief.ac \home\torcs\essai\games\torcs\tracks\e-track-5\e-track-5-relief.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\e-track-6
copy .\data\tracks\e-track-6\e-track-6.xml \home\torcs\essai\games\torcs\tracks\e-track-6\e-track-6.xml
copy .\data\tracks\e-track-6\background.png \home\torcs\essai\games\torcs\tracks\e-track-6\background.png
copy .\data\tracks\e-track-6\e-track-6.ac \home\torcs\essai\games\torcs\tracks\e-track-6\e-track-6.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\g-track-1
copy .\data\tracks\g-track-1\g-track-1.xml \home\torcs\essai\games\torcs\tracks\g-track-1\g-track-1.xml
copy .\data\tracks\g-track-1\g-track-1.ac \home\torcs\essai\games\torcs\tracks\g-track-1\g-track-1.ac
copy .\data\tracks\g-track-1\background.png \home\torcs\essai\games\torcs\tracks\g-track-1\background.png
copy .\data\tracks\g-track-1\alltree2.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\alltree2.rgb
copy .\data\tracks\g-track-1\alltree.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\alltree.rgb
copy .\data\tracks\g-track-1\asphalt2.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\asphalt2.rgb
copy .\data\tracks\g-track-1\asphalt3.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\asphalt3.rgb
copy .\data\tracks\g-track-1\env.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\env.rgb
copy .\data\tracks\g-track-1\grassg1.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\grassg1.rgb
copy .\data\tracks\g-track-1\grassg2.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\grassg2.rgb
copy .\data\tracks\g-track-1\grassg3.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\grassg3.rgb
copy .\data\tracks\g-track-1\rock2.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\rock2.rgb
copy .\data\tracks\g-track-1\rock3.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\rock3.rgb
copy .\data\tracks\g-track-1\texte1.rgb \home\torcs\essai\games\torcs\tracks\g-track-1\texte1.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\michigan
copy .\data\tracks\michigan\michigan.xml \home\torcs\essai\games\torcs\tracks\michigan\michigan.xml
copy .\data\tracks\michigan\background.png \home\torcs\essai\games\torcs\tracks\michigan\background.png
copy .\data\tracks\michigan\michigan.ac \home\torcs\essai\games\torcs\tracks\michigan\michigan.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\mixed-1
copy .\data\tracks\mixed-1\mixed-1.xml \home\torcs\essai\games\torcs\tracks\mixed-1\mixed-1.xml
copy .\data\tracks\mixed-1\mixed-1.ac \home\torcs\essai\games\torcs\tracks\mixed-1\mixed-1.ac
copy .\data\tracks\mixed-1\background.png \home\torcs\essai\games\torcs\tracks\mixed-1\background.png
copy .\data\tracks\mixed-1\env1.png \home\torcs\essai\games\torcs\tracks\mixed-1\env1.png

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tracks
call .\create_dir .\home\torcs\essai\games\torcs\tracks\mixed-2
copy .\data\tracks\mixed-2\mixed-2.xml \home\torcs\essai\games\torcs\tracks\mixed-2\mixed-2.xml
copy .\data\tracks\mixed-2\background.png \home\torcs\essai\games\torcs\tracks\mixed-2\background.png
copy .\data\tracks\mixed-2\env.rgb \home\torcs\essai\games\torcs\tracks\mixed-2\env.rgb
copy .\data\tracks\mixed-2\mixed-2.ac \home\torcs\essai\games\torcs\tracks\mixed-2\mixed-2.ac

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\cylos1
call .\create_dir .\home\torcs\essai\games\torcs\drivers\cylos1\tracksdata
copy .\src\drivers\cylos1\tracksdata\car_e-track-3.xml \home\torcs\essai\games\torcs\drivers\cylos1\tracksdata\car_e-track-3.xml
copy .\src\drivers\cylos1\tracksdata\car_lemans.xml \home\torcs\essai\games\torcs\drivers\cylos1\tracksdata\car_lemans.xml
copy .\src\drivers\cylos1\tracksdata\car_test-1.xml \home\torcs\essai\games\torcs\drivers\cylos1\tracksdata\car_test-1.xml
copy .\src\drivers\cylos1\tracksdata\lemans.xml \home\torcs\essai\games\torcs\drivers\cylos1\tracksdata\lemans.xml
copy .\src\drivers\cylos1\tracksdata\michigan.xml \home\torcs\essai\games\torcs\drivers\cylos1\tracksdata\michigan.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\cylos1
copy .\src\drivers\cylos1\cylos1.xml \home\torcs\essai\games\torcs\drivers\cylos1\cylos1.xml
copy .\src\drivers\cylos1\car1.xml \home\torcs\essai\games\torcs\drivers\cylos1\car1.xml
copy .\src\drivers\cylos1\cg-nascar-rwd.rgb \home\torcs\essai\games\torcs\drivers\cylos1\cg-nascar-rwd.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\1
copy .\src\drivers\damned\1\car.xml \home\torcs\essai\games\torcs\drivers\damned\1\car.xml
copy .\src\drivers\damned\1\buggy.rgb \home\torcs\essai\games\torcs\drivers\damned\1\buggy.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\10
copy .\src\drivers\damned\10\car.xml \home\torcs\essai\games\torcs\drivers\damned\10\car.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\2
copy .\src\drivers\damned\2\car.xml \home\torcs\essai\games\torcs\drivers\damned\2\car.xml
copy .\src\drivers\damned\2\buggy.rgb \home\torcs\essai\games\torcs\drivers\damned\2\buggy.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\3
copy .\src\drivers\damned\3\p406.rgb \home\torcs\essai\games\torcs\drivers\damned\3\p406.rgb
copy .\src\drivers\damned\3\car.xml \home\torcs\essai\games\torcs\drivers\damned\3\car.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\4
copy .\src\drivers\damned\4\p406.rgb \home\torcs\essai\games\torcs\drivers\damned\4\p406.rgb
copy .\src\drivers\damned\4\car.xml \home\torcs\essai\games\torcs\drivers\damned\4\car.xml
copy .\src\drivers\damned\4\torcs.rgb \home\torcs\essai\games\torcs\drivers\damned\4\torcs.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\5
copy .\src\drivers\damned\5\car.xml \home\torcs\essai\games\torcs\drivers\damned\5\car.xml
copy .\src\drivers\damned\5\acura-nsx-sz.rgb \home\torcs\essai\games\torcs\drivers\damned\5\acura-nsx-sz.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\6
copy .\src\drivers\damned\6\acura-nsx-sz.rgb \home\torcs\essai\games\torcs\drivers\damned\6\acura-nsx-sz.rgb
copy .\src\drivers\damned\6\car.xml \home\torcs\essai\games\torcs\drivers\damned\6\car.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\7
copy .\src\drivers\damned\7\viper-gts-r.rgb \home\torcs\essai\games\torcs\drivers\damned\7\viper-gts-r.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned\8
copy .\src\drivers\damned\8\car.xml \home\torcs\essai\games\torcs\drivers\damned\8\car.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\damned
copy .\src\drivers\damned\damned.xml \home\torcs\essai\games\torcs\drivers\damned\damned.xml
copy .\src\drivers\damned\car1.xml \home\torcs\essai\games\torcs\drivers\damned\car1.xml
copy .\src\drivers\damned\logo.rgb \home\torcs\essai\games\torcs\drivers\damned\logo.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\cg-gt-rwd
copy .\src\drivers\human\cg-gt-rwd\skin.png \home\torcs\essai\games\torcs\drivers\human\cg-gt-rwd\skin.png
copy .\src\drivers\human\cg-gt-rwd\skin.rgb \home\torcs\essai\games\torcs\drivers\human\cg-gt-rwd\skin.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\dirt-1
copy .\src\drivers\human\tracks\dirt-1\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\dirt-1\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\dirt-2
copy .\src\drivers\human\tracks\dirt-2\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\dirt-2\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\dirt-3
copy .\src\drivers\human\tracks\dirt-3\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\dirt-3\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\dirt-4
copy .\src\drivers\human\tracks\dirt-4\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\dirt-4\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\dirt-5
copy .\src\drivers\human\tracks\dirt-5\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\dirt-5\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\dirt-6
copy .\src\drivers\human\tracks\dirt-6\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\dirt-6\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\e-track-1
copy .\src\drivers\human\tracks\e-track-1\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-1\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\e-track-2
copy .\src\drivers\human\tracks\e-track-2\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-2\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\e-track-3
copy .\src\drivers\human\tracks\e-track-3\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-3\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\e-track-4
copy .\src\drivers\human\tracks\e-track-4\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-4\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\e-track-5
copy .\src\drivers\human\tracks\e-track-5\car-cg-nascar-rwd.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-5\car-cg-nascar-rwd.xml
copy .\src\drivers\human\tracks\e-track-5\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-5\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\e-track-6
copy .\src\drivers\human\tracks\e-track-6\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\e-track-6\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\mixed-1
copy .\src\drivers\human\tracks\mixed-1\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\mixed-1\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human\tracks\mixed-2
copy .\src\drivers\human\tracks\mixed-2\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\tracks\mixed-2\car-torcs.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\human
copy .\src\drivers\human\car-buggy.xml \home\torcs\essai\games\torcs\drivers\human\car-buggy.xml
copy .\src\drivers\human\car-cg-gt-rwd.xml \home\torcs\essai\games\torcs\drivers\human\car-cg-gt-rwd.xml
copy .\src\drivers\human\car-cg-nascar-fwd.xml \home\torcs\essai\games\torcs\drivers\human\car-cg-nascar-fwd.xml
copy .\src\drivers\human\car-cg-nascar-rwd.xml \home\torcs\essai\games\torcs\drivers\human\car-cg-nascar-rwd.xml
copy .\src\drivers\human\car-lotus-gt1.xml \home\torcs\essai\games\torcs\drivers\human\car-lotus-gt1.xml
copy .\src\drivers\human\car-mclaren-f1.xml \home\torcs\essai\games\torcs\drivers\human\car-mclaren-f1.xml
copy .\src\drivers\human\car-p406.xml \home\torcs\essai\games\torcs\drivers\human\car-p406.xml
copy .\src\drivers\human\car-torcs.xml \home\torcs\essai\games\torcs\drivers\human\car-torcs.xml
copy .\src\drivers\human\car-viper-gts-r.xml \home\torcs\essai\games\torcs\drivers\human\car-viper-gts-r.xml
copy .\src\drivers\human\human.xml \home\torcs\essai\games\torcs\drivers\human\human.xml
copy .\src\drivers\human\preferences.xml \home\torcs\essai\games\torcs\drivers\human\preferences.xml
copy .\src\drivers\human\logo.rgb \home\torcs\essai\games\torcs\drivers\human\logo.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\K1999
copy .\src\drivers\K1999\K1999.xml \home\torcs\essai\games\torcs\drivers\K1999\K1999.xml
copy .\src\drivers\K1999\settings.xml \home\torcs\essai\games\torcs\drivers\K1999\settings.xml
copy .\src\drivers\K1999\logo.rgb \home\torcs\essai\games\torcs\drivers\K1999\logo.rgb
copy .\src\drivers\K1999\cg-nascar-rwd.rgb \home\torcs\essai\games\torcs\drivers\K1999\cg-nascar-rwd.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\lliaw
call .\create_dir .\home\torcs\essai\games\torcs\drivers\lliaw\tracksdata
copy .\src\drivers\lliaw\tracksdata\car_e-track-3.xml \home\torcs\essai\games\torcs\drivers\lliaw\tracksdata\car_e-track-3.xml
copy .\src\drivers\lliaw\tracksdata\car_e-track-4.xml \home\torcs\essai\games\torcs\drivers\lliaw\tracksdata\car_e-track-4.xml
copy .\src\drivers\lliaw\tracksdata\car_e-track-6.xml \home\torcs\essai\games\torcs\drivers\lliaw\tracksdata\car_e-track-6.xml
copy .\src\drivers\lliaw\tracksdata\car_eroad.xml \home\torcs\essai\games\torcs\drivers\lliaw\tracksdata\car_eroad.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\lliaw
copy .\src\drivers\lliaw\lliaw.xml \home\torcs\essai\games\torcs\drivers\lliaw\lliaw.xml
copy .\src\drivers\lliaw\car.xml \home\torcs\essai\games\torcs\drivers\lliaw\car.xml
copy .\src\drivers\lliaw\viper-gts-r.rgb \home\torcs\essai\games\torcs\drivers\lliaw\viper-gts-r.rgb
copy .\src\drivers\lliaw\logo.rgb \home\torcs\essai\games\torcs\drivers\lliaw\logo.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\tanhoj
call .\create_dir .\home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata
copy .\src\drivers\tanhoj\tracksdata\aalborg.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\aalborg.xml
copy .\src\drivers\tanhoj\tracksdata\car_aalborg.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_aalborg.xml
copy .\src\drivers\tanhoj\tracksdata\car_e-track-1.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_e-track-1.xml
copy .\src\drivers\tanhoj\tracksdata\car_e-track-2.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_e-track-2.xml
copy .\src\drivers\tanhoj\tracksdata\car_e-track-3.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_e-track-3.xml
copy .\src\drivers\tanhoj\tracksdata\car_e-track-4.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_e-track-4.xml
copy .\src\drivers\tanhoj\tracksdata\car_e-track-5.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_e-track-5.xml
copy .\src\drivers\tanhoj\tracksdata\car_e-track-6.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_e-track-6.xml
copy .\src\drivers\tanhoj\tracksdata\car_g-track-1.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_g-track-1.xml
copy .\src\drivers\tanhoj\tracksdata\car_s2.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_s2.xml
copy .\src\drivers\tanhoj\tracksdata\car_test-1.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\car_test-1.xml
copy .\src\drivers\tanhoj\tracksdata\e-track-1.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\e-track-1.xml
copy .\src\drivers\tanhoj\tracksdata\e-track-2.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\e-track-2.xml
copy .\src\drivers\tanhoj\tracksdata\e-track-3.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\e-track-3.xml
copy .\src\drivers\tanhoj\tracksdata\e-track-4.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\e-track-4.xml
copy .\src\drivers\tanhoj\tracksdata\e-track-5.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\e-track-5.xml
copy .\src\drivers\tanhoj\tracksdata\e-track-6.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\e-track-6.xml
copy .\src\drivers\tanhoj\tracksdata\g-track-1.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\g-track-1.xml
copy .\src\drivers\tanhoj\tracksdata\michigan.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\michigan.xml
copy .\src\drivers\tanhoj\tracksdata\s2.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tracksdata\s2.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\tanhoj
copy .\src\drivers\tanhoj\tanhoj.xml \home\torcs\essai\games\torcs\drivers\tanhoj\tanhoj.xml
copy .\src\drivers\tanhoj\car1.xml \home\torcs\essai\games\torcs\drivers\tanhoj\car1.xml
copy .\src\drivers\tanhoj\logo.rgb \home\torcs\essai\games\torcs\drivers\tanhoj\logo.rgb
copy .\src\drivers\tanhoj\cg-nascar-rwd.rgb \home\torcs\essai\games\torcs\drivers\tanhoj\cg-nascar-rwd.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\tita
copy .\src\drivers\tita\tita.xml \home\torcs\essai\games\torcs\drivers\tita\tita.xml
copy .\src\drivers\tita\car.xml \home\torcs\essai\games\torcs\drivers\tita\car.xml
copy .\src\drivers\tita\logo.rgb \home\torcs\essai\games\torcs\drivers\tita\logo.rgb
copy .\src\drivers\tita\lotus-gt1.rgb \home\torcs\essai\games\torcs\drivers\tita\lotus-gt1.rgb

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\tutorial1
copy .\src\drivers\tutorial1\tutorial1.xml \home\torcs\essai\games\torcs\drivers\tutorial1\tutorial1.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\drivers
call .\create_dir .\home\torcs\essai\games\torcs\drivers\tutorial2
copy .\src\drivers\tutorial2\tutorial2.xml \home\torcs\essai\games\torcs\drivers\tutorial2\tutorial2.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\config
copy .\src\libs\tgf\screen.xml \home\torcs\essai\games\torcs\config\screen.xml
copy .\src\libs\tgf\params.dtd \home\torcs\essai\games\torcs\config\params.dtd

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\config
call .\create_dir .\home\torcs\essai\games\torcs\config\practice
copy .\src\modules\raceman\practice\practice\practice.xml \home\torcs\essai\games\torcs\config\practice\practice.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\config
call .\create_dir .\home\torcs\essai\games\torcs\config\quickrace
copy .\src\modules\raceman\quickrace\qrace.xml \home\torcs\essai\games\torcs\config\quickrace\qrace.xml

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\telemetry
copy .\src\modules\telemetry\telemetry.sh \home\torcs\essai\games\torcs\telemetry\telemetry.sh

call .\create_dir .\home
call .\create_dir .\home\torcs
call .\create_dir .\home\torcs\essai
call .\create_dir .\home\torcs\essai\games
call .\create_dir .\home\torcs\essai\games\torcs
call .\create_dir .\home\torcs\essai\games\torcs\tools
call .\create_dir .\home\torcs\essai\games\torcs\tools\trackgen
copy .\src\tools\trackgen\trackgen.xml \home\torcs\essai\games\torcs\tools\trackgen\trackgen.xml
