@echo off
echo Checking directories ...


call .\create_dir .\runtimed
call .\create_dir .\runtimed\config
copy .\src\modules\graphic\ssggraph\graph.xml .\runtimed\config\graph.xml

call .\create_dir .\runtimed
call .\create_dir .\runtimed\modules
call .\create_dir .\runtimed\modules\graphic

call .\create_dir .\runtimed
call .\create_dir .\runtimed\data
call .\create_dir .\runtimed\data\textures
copy .\data\data\textures\background.png .\runtimed\data\textures\background.png
copy .\data\data\textures\logo.png .\runtimed\data\textures\logo.png
copy .\data\data\textures\pylon1.png .\runtimed\data\textures\pylon1.png
copy .\data\data\textures\pylon2.png .\runtimed\data\textures\pylon2.png
copy .\data\data\textures\pylon3.png .\runtimed\data\textures\pylon3.png
copy .\data\data\textures\tr-asphalt-both.png .\runtimed\data\textures\tr-asphalt-both.png
copy .\data\data\textures\tr-asphalt-left.png .\runtimed\data\textures\tr-asphalt-left.png
copy .\data\data\textures\tr-asphalt-l.png .\runtimed\data\textures\tr-asphalt-l.png
copy .\data\data\textures\tr-asphalt.png .\runtimed\data\textures\tr-asphalt.png
copy .\data\data\textures\tr-asphalt-p.png .\runtimed\data\textures\tr-asphalt-p.png
copy .\data\data\textures\tr-asphalt-right.png .\runtimed\data\textures\tr-asphalt-right.png
copy .\data\data\textures\tr-barrier.png .\runtimed\data\textures\tr-barrier.png
copy .\data\data\textures\tr-concrete.png .\runtimed\data\textures\tr-concrete.png
copy .\data\data\textures\tr-dirtb.png .\runtimed\data\textures\tr-dirtb.png
copy .\data\data\textures\tr-dirt.png .\runtimed\data\textures\tr-dirt.png
copy .\data\data\textures\tr-grass.png .\runtimed\data\textures\tr-grass.png
copy .\data\data\textures\tr-sand.png .\runtimed\data\textures\tr-sand.png
copy .\data\data\textures\back-sign.rgb .\runtimed\data\textures\back-sign.rgb
copy .\data\data\textures\building1.rgb .\runtimed\data\textures\building1.rgb
copy .\data\data\textures\building2.rgb .\runtimed\data\textures\building2.rgb
copy .\data\data\textures\concrete2.rgb .\runtimed\data\textures\concrete2.rgb
copy .\data\data\textures\concrete.rgb .\runtimed\data\textures\concrete.rgb
copy .\data\data\textures\counter-bg-10.rgb .\runtimed\data\textures\counter-bg-10.rgb
copy .\data\data\textures\counter-bg2.rgb .\runtimed\data\textures\counter-bg2.rgb
copy .\data\data\textures\counter-bg.rgb .\runtimed\data\textures\counter-bg.rgb
copy .\data\data\textures\counter-bg-rpm.rgb .\runtimed\data\textures\counter-bg-rpm.rgb
copy .\data\data\textures\counter.rgb .\runtimed\data\textures\counter.rgb
copy .\data\data\textures\env.rgb .\runtimed\data\textures\env.rgb
copy .\data\data\textures\forest1.rgb .\runtimed\data\textures\forest1.rgb
copy .\data\data\textures\forest2.rgb .\runtimed\data\textures\forest2.rgb
copy .\data\data\textures\forest3.rgb .\runtimed\data\textures\forest3.rgb
copy .\data\data\textures\grassg1.rgb .\runtimed\data\textures\grassg1.rgb
copy .\data\data\textures\grassg2.rgb .\runtimed\data\textures\grassg2.rgb
copy .\data\data\textures\grassg3.rgb .\runtimed\data\textures\grassg3.rgb
copy .\data\data\textures\logo.rgb .\runtimed\data\textures\logo.rgb
copy .\data\data\textures\panel-empty.rgb .\runtimed\data\textures\panel-empty.rgb
copy .\data\data\textures\parking1.rgb .\runtimed\data\textures\parking1.rgb
copy .\data\data\textures\people1.rgb .\runtimed\data\textures\people1.rgb
copy .\data\data\textures\pit-left.rgb .\runtimed\data\textures\pit-left.rgb
copy .\data\data\textures\pit-right.rgb .\runtimed\data\textures\pit-right.rgb
copy .\data\data\textures\pylon1.rgb .\runtimed\data\textures\pylon1.rgb
copy .\data\data\textures\pylon2.rgb .\runtimed\data\textures\pylon2.rgb
copy .\data\data\textures\pylon3.rgb .\runtimed\data\textures\pylon3.rgb
copy .\data\data\textures\red-light-off.rgb .\runtimed\data\textures\red-light-off.rgb
copy .\data\data\textures\red-light-on.rgb .\runtimed\data\textures\red-light-on.rgb
copy .\data\data\textures\rim1.rgb .\runtimed\data\textures\rim1.rgb
copy .\data\data\textures\rim2.rgb .\runtimed\data\textures\rim2.rgb
copy .\data\data\textures\rim3.rgb .\runtimed\data\textures\rim3.rgb
copy .\data\data\textures\rock2.rgb .\runtimed\data\textures\rock2.rgb
copy .\data\data\textures\rock3.rgb .\runtimed\data\textures\rock3.rgb
copy .\data\data\textures\rpm5500.rgb .\runtimed\data\textures\rpm5500.rgb
copy .\data\data\textures\rpm7000.rgb .\runtimed\data\textures\rpm7000.rgb
copy .\data\data\textures\rpm8000.rgb .\runtimed\data\textures\rpm8000.rgb
copy .\data\data\textures\rpm8500.rgb .\runtimed\data\textures\rpm8500.rgb
copy .\data\data\textures\speed240.rgb .\runtimed\data\textures\speed240.rgb
copy .\data\data\textures\speed300.rgb .\runtimed\data\textures\speed300.rgb
copy .\data\data\textures\speed360.rgb .\runtimed\data\textures\speed360.rgb
copy .\data\data\textures\torcs-ad1.rgb .\runtimed\data\textures\torcs-ad1.rgb
copy .\data\data\textures\tr-asphalt-both_nmm.rgb .\runtimed\data\textures\tr-asphalt-both_nmm.rgb
copy .\data\data\textures\tr-asphalt-both.rgb .\runtimed\data\textures\tr-asphalt-both.rgb
copy .\data\data\textures\tr-asphalt-left_nmm.rgb .\runtimed\data\textures\tr-asphalt-left_nmm.rgb
copy .\data\data\textures\tr-asphalt-left.rgb .\runtimed\data\textures\tr-asphalt-left.rgb
copy .\data\data\textures\tr-asphalt-l_nmm.rgb .\runtimed\data\textures\tr-asphalt-l_nmm.rgb
copy .\data\data\textures\tr-asphalt-l.rgb .\runtimed\data\textures\tr-asphalt-l.rgb
copy .\data\data\textures\tr-asphalt_nmm.rgb .\runtimed\data\textures\tr-asphalt_nmm.rgb
copy .\data\data\textures\tr-asphalt-p_nmm.rgb .\runtimed\data\textures\tr-asphalt-p_nmm.rgb
copy .\data\data\textures\tr-asphalt-p.rgb .\runtimed\data\textures\tr-asphalt-p.rgb
copy .\data\data\textures\tr-asphalt.rgb .\runtimed\data\textures\tr-asphalt.rgb
copy .\data\data\textures\tr-asphalt-right_nmm.rgb .\runtimed\data\textures\tr-asphalt-right_nmm.rgb
copy .\data\data\textures\tr-asphalt-right.rgb .\runtimed\data\textures\tr-asphalt-right.rgb
copy .\data\data\textures\tr-barrier.rgb .\runtimed\data\textures\tr-barrier.rgb
copy .\data\data\textures\tr-concrete_nmm.rgb .\runtimed\data\textures\tr-concrete_nmm.rgb
copy .\data\data\textures\tr-concrete.rgb .\runtimed\data\textures\tr-concrete.rgb
copy .\data\data\textures\tr-dirtb.rgb .\runtimed\data\textures\tr-dirtb.rgb
copy .\data\data\textures\tr-dirt.rgb .\runtimed\data\textures\tr-dirt.rgb
copy .\data\data\textures\tree10.rgb .\runtimed\data\textures\tree10.rgb
copy .\data\data\textures\tree11.rgb .\runtimed\data\textures\tree11.rgb
copy .\data\data\textures\tree12.rgb .\runtimed\data\textures\tree12.rgb
copy .\data\data\textures\tree13.rgb .\runtimed\data\textures\tree13.rgb
copy .\data\data\textures\tree14.rgb .\runtimed\data\textures\tree14.rgb
copy .\data\data\textures\tree15.rgb .\runtimed\data\textures\tree15.rgb
copy .\data\data\textures\tree16.rgb .\runtimed\data\textures\tree16.rgb
copy .\data\data\textures\tree17.rgb .\runtimed\data\textures\tree17.rgb
copy .\data\data\textures\tree1.rgb .\runtimed\data\textures\tree1.rgb
copy .\data\data\textures\tree2.rgb .\runtimed\data\textures\tree2.rgb
copy .\data\data\textures\tree3.rgb .\runtimed\data\textures\tree3.rgb
copy .\data\data\textures\tree4.rgb .\runtimed\data\textures\tree4.rgb
copy .\data\data\textures\tree5.rgb .\runtimed\data\textures\tree5.rgb
copy .\data\data\textures\tree7.rgb .\runtimed\data\textures\tree7.rgb
copy .\data\data\textures\tree8.rgb .\runtimed\data\textures\tree8.rgb
copy .\data\data\textures\tree9.rgb .\runtimed\data\textures\tree9.rgb
copy .\data\data\textures\tr-grass2.rgb .\runtimed\data\textures\tr-grass2.rgb
copy .\data\data\textures\tr-grass.rgb .\runtimed\data\textures\tr-grass.rgb
copy .\data\data\textures\tr-sand2.rgb .\runtimed\data\textures\tr-sand2.rgb
copy .\data\data\textures\tr-sand.rgb .\runtimed\data\textures\tr-sand.rgb
copy .\data\data\textures\tr-snow.rgb .\runtimed\data\textures\tr-snow.rgb
copy .\data\data\textures\tr-water.rgb .\runtimed\data\textures\tr-water.rgb
copy .\data\data\textures\turn100L.rgb .\runtimed\data\textures\turn100L.rgb
copy .\data\data\textures\turn100R.rgb .\runtimed\data\textures\turn100R.rgb
copy .\data\data\textures\turn150L.rgb .\runtimed\data\textures\turn150L.rgb
copy .\data\data\textures\turn150R.rgb .\runtimed\data\textures\turn150R.rgb
copy .\data\data\textures\turn200L.rgb .\runtimed\data\textures\turn200L.rgb
copy .\data\data\textures\turn200R.rgb .\runtimed\data\textures\turn200R.rgb
copy .\data\data\textures\turn300L.rgb .\runtimed\data\textures\turn300L.rgb
copy .\data\data\textures\turn300R.rgb .\runtimed\data\textures\turn300R.rgb
copy .\data\data\textures\turn50L.rgb .\runtimed\data\textures\turn50L.rgb
copy .\data\data\textures\turn50R.rgb .\runtimed\data\textures\turn50R.rgb
