@echo off
echo Checking directories ...


call .\create_dir .\runtime
call .\create_dir .\runtime\config
copy .\src\modules\graphic\ssggraph\graph.xml .\runtime\config\graph.xml

call .\create_dir .\runtime
call .\create_dir .\runtime\modules
call .\create_dir .\runtime\modules\graphic

call .\create_dir .\runtime
call .\create_dir .\runtime\data
call .\create_dir .\runtime\data\textures
copy .\data\data\textures\background.png .\runtime\data\textures\background.png
copy .\data\data\textures\logo.png .\runtime\data\textures\logo.png
copy .\data\data\textures\pylon1.png .\runtime\data\textures\pylon1.png
copy .\data\data\textures\pylon2.png .\runtime\data\textures\pylon2.png
copy .\data\data\textures\pylon3.png .\runtime\data\textures\pylon3.png
copy .\data\data\textures\tr-asphalt-both.png .\runtime\data\textures\tr-asphalt-both.png
copy .\data\data\textures\tr-asphalt-left.png .\runtime\data\textures\tr-asphalt-left.png
copy .\data\data\textures\tr-asphalt-l.png .\runtime\data\textures\tr-asphalt-l.png
copy .\data\data\textures\tr-asphalt.png .\runtime\data\textures\tr-asphalt.png
copy .\data\data\textures\tr-asphalt-p.png .\runtime\data\textures\tr-asphalt-p.png
copy .\data\data\textures\tr-asphalt-right.png .\runtime\data\textures\tr-asphalt-right.png
copy .\data\data\textures\tr-barrier.png .\runtime\data\textures\tr-barrier.png
copy .\data\data\textures\tr-concrete.png .\runtime\data\textures\tr-concrete.png
copy .\data\data\textures\tr-dirtb.png .\runtime\data\textures\tr-dirtb.png
copy .\data\data\textures\tr-dirt.png .\runtime\data\textures\tr-dirt.png
copy .\data\data\textures\tr-grass.png .\runtime\data\textures\tr-grass.png
copy .\data\data\textures\tr-sand.png .\runtime\data\textures\tr-sand.png
copy .\data\data\textures\back-sign.rgb .\runtime\data\textures\back-sign.rgb
copy .\data\data\textures\building1.rgb .\runtime\data\textures\building1.rgb
copy .\data\data\textures\building2.rgb .\runtime\data\textures\building2.rgb
copy .\data\data\textures\concrete2.rgb .\runtime\data\textures\concrete2.rgb
copy .\data\data\textures\concrete.rgb .\runtime\data\textures\concrete.rgb
copy .\data\data\textures\counter-bg-10.rgb .\runtime\data\textures\counter-bg-10.rgb
copy .\data\data\textures\counter-bg2.rgb .\runtime\data\textures\counter-bg2.rgb
copy .\data\data\textures\counter-bg.rgb .\runtime\data\textures\counter-bg.rgb
copy .\data\data\textures\counter-bg-rpm.rgb .\runtime\data\textures\counter-bg-rpm.rgb
copy .\data\data\textures\counter.rgb .\runtime\data\textures\counter.rgb
copy .\data\data\textures\env.rgb .\runtime\data\textures\env.rgb
copy .\data\data\textures\forest1.rgb .\runtime\data\textures\forest1.rgb
copy .\data\data\textures\forest2.rgb .\runtime\data\textures\forest2.rgb
copy .\data\data\textures\forest3.rgb .\runtime\data\textures\forest3.rgb
copy .\data\data\textures\grassg1.rgb .\runtime\data\textures\grassg1.rgb
copy .\data\data\textures\grassg2.rgb .\runtime\data\textures\grassg2.rgb
copy .\data\data\textures\grassg3.rgb .\runtime\data\textures\grassg3.rgb
copy .\data\data\textures\logo.rgb .\runtime\data\textures\logo.rgb
copy .\data\data\textures\panel-empty.rgb .\runtime\data\textures\panel-empty.rgb
copy .\data\data\textures\parking1.rgb .\runtime\data\textures\parking1.rgb
copy .\data\data\textures\people1.rgb .\runtime\data\textures\people1.rgb
copy .\data\data\textures\pit-left.rgb .\runtime\data\textures\pit-left.rgb
copy .\data\data\textures\pit-right.rgb .\runtime\data\textures\pit-right.rgb
copy .\data\data\textures\pylon1.rgb .\runtime\data\textures\pylon1.rgb
copy .\data\data\textures\pylon2.rgb .\runtime\data\textures\pylon2.rgb
copy .\data\data\textures\pylon3.rgb .\runtime\data\textures\pylon3.rgb
copy .\data\data\textures\red-light-off.rgb .\runtime\data\textures\red-light-off.rgb
copy .\data\data\textures\red-light-on.rgb .\runtime\data\textures\red-light-on.rgb
copy .\data\data\textures\rim1.rgb .\runtime\data\textures\rim1.rgb
copy .\data\data\textures\rim2.rgb .\runtime\data\textures\rim2.rgb
copy .\data\data\textures\rim3.rgb .\runtime\data\textures\rim3.rgb
copy .\data\data\textures\rock2.rgb .\runtime\data\textures\rock2.rgb
copy .\data\data\textures\rock3.rgb .\runtime\data\textures\rock3.rgb
copy .\data\data\textures\rpm5500.rgb .\runtime\data\textures\rpm5500.rgb
copy .\data\data\textures\rpm7000.rgb .\runtime\data\textures\rpm7000.rgb
copy .\data\data\textures\rpm8000.rgb .\runtime\data\textures\rpm8000.rgb
copy .\data\data\textures\rpm8500.rgb .\runtime\data\textures\rpm8500.rgb
copy .\data\data\textures\speed240.rgb .\runtime\data\textures\speed240.rgb
copy .\data\data\textures\speed300.rgb .\runtime\data\textures\speed300.rgb
copy .\data\data\textures\speed360.rgb .\runtime\data\textures\speed360.rgb
copy .\data\data\textures\torcs-ad1.rgb .\runtime\data\textures\torcs-ad1.rgb
copy .\data\data\textures\tr-asphalt-both_nmm.rgb .\runtime\data\textures\tr-asphalt-both_nmm.rgb
copy .\data\data\textures\tr-asphalt-both.rgb .\runtime\data\textures\tr-asphalt-both.rgb
copy .\data\data\textures\tr-asphalt-left_nmm.rgb .\runtime\data\textures\tr-asphalt-left_nmm.rgb
copy .\data\data\textures\tr-asphalt-left.rgb .\runtime\data\textures\tr-asphalt-left.rgb
copy .\data\data\textures\tr-asphalt-l_nmm.rgb .\runtime\data\textures\tr-asphalt-l_nmm.rgb
copy .\data\data\textures\tr-asphalt-l.rgb .\runtime\data\textures\tr-asphalt-l.rgb
copy .\data\data\textures\tr-asphalt_nmm.rgb .\runtime\data\textures\tr-asphalt_nmm.rgb
copy .\data\data\textures\tr-asphalt-p_nmm.rgb .\runtime\data\textures\tr-asphalt-p_nmm.rgb
copy .\data\data\textures\tr-asphalt-p.rgb .\runtime\data\textures\tr-asphalt-p.rgb
copy .\data\data\textures\tr-asphalt.rgb .\runtime\data\textures\tr-asphalt.rgb
copy .\data\data\textures\tr-asphalt-right_nmm.rgb .\runtime\data\textures\tr-asphalt-right_nmm.rgb
copy .\data\data\textures\tr-asphalt-right.rgb .\runtime\data\textures\tr-asphalt-right.rgb
copy .\data\data\textures\tr-barrier.rgb .\runtime\data\textures\tr-barrier.rgb
copy .\data\data\textures\tr-concrete_nmm.rgb .\runtime\data\textures\tr-concrete_nmm.rgb
copy .\data\data\textures\tr-concrete.rgb .\runtime\data\textures\tr-concrete.rgb
copy .\data\data\textures\tr-dirtb.rgb .\runtime\data\textures\tr-dirtb.rgb
copy .\data\data\textures\tr-dirt.rgb .\runtime\data\textures\tr-dirt.rgb
copy .\data\data\textures\tree10.rgb .\runtime\data\textures\tree10.rgb
copy .\data\data\textures\tree11.rgb .\runtime\data\textures\tree11.rgb
copy .\data\data\textures\tree12.rgb .\runtime\data\textures\tree12.rgb
copy .\data\data\textures\tree13.rgb .\runtime\data\textures\tree13.rgb
copy .\data\data\textures\tree14.rgb .\runtime\data\textures\tree14.rgb
copy .\data\data\textures\tree15.rgb .\runtime\data\textures\tree15.rgb
copy .\data\data\textures\tree16.rgb .\runtime\data\textures\tree16.rgb
copy .\data\data\textures\tree17.rgb .\runtime\data\textures\tree17.rgb
copy .\data\data\textures\tree1.rgb .\runtime\data\textures\tree1.rgb
copy .\data\data\textures\tree2.rgb .\runtime\data\textures\tree2.rgb
copy .\data\data\textures\tree3.rgb .\runtime\data\textures\tree3.rgb
copy .\data\data\textures\tree4.rgb .\runtime\data\textures\tree4.rgb
copy .\data\data\textures\tree5.rgb .\runtime\data\textures\tree5.rgb
copy .\data\data\textures\tree7.rgb .\runtime\data\textures\tree7.rgb
copy .\data\data\textures\tree8.rgb .\runtime\data\textures\tree8.rgb
copy .\data\data\textures\tree9.rgb .\runtime\data\textures\tree9.rgb
copy .\data\data\textures\tr-grass2.rgb .\runtime\data\textures\tr-grass2.rgb
copy .\data\data\textures\tr-grass.rgb .\runtime\data\textures\tr-grass.rgb
copy .\data\data\textures\tr-sand2.rgb .\runtime\data\textures\tr-sand2.rgb
copy .\data\data\textures\tr-sand.rgb .\runtime\data\textures\tr-sand.rgb
copy .\data\data\textures\tr-snow.rgb .\runtime\data\textures\tr-snow.rgb
copy .\data\data\textures\tr-water.rgb .\runtime\data\textures\tr-water.rgb
copy .\data\data\textures\turn100L.rgb .\runtime\data\textures\turn100L.rgb
copy .\data\data\textures\turn100R.rgb .\runtime\data\textures\turn100R.rgb
copy .\data\data\textures\turn150L.rgb .\runtime\data\textures\turn150L.rgb
copy .\data\data\textures\turn150R.rgb .\runtime\data\textures\turn150R.rgb
copy .\data\data\textures\turn200L.rgb .\runtime\data\textures\turn200L.rgb
copy .\data\data\textures\turn200R.rgb .\runtime\data\textures\turn200R.rgb
copy .\data\data\textures\turn300L.rgb .\runtime\data\textures\turn300L.rgb
copy .\data\data\textures\turn300R.rgb .\runtime\data\textures\turn300R.rgb
copy .\data\data\textures\turn50L.rgb .\runtime\data\textures\turn50L.rgb
copy .\data\data\textures\turn50R.rgb .\runtime\data\textures\turn50R.rgb
