##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 25 01:32:41 CET 2001
#    copyright            : (C) 2001 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################




DATADIR   = cars/360-modena

DATA      = 360-modena.xml  360-modena.ac \
	    360-modena-lod1.ac texmapper.xml \
	    tex-wheel.rgb 360-modena.rgb

data_PKGFILES	= $(DATA)

data_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}



