##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 18 21:02:29 /etc/localtime 2001
#    copyright            : (C) 2000 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################



DATADIR   = cars/baja-bug

DATA      = baja-bug-base.ac baja-bug.ac baja-bug.acc baja-bug.rgb baja-bug.xml texmapper.xml tex-wheel.rgb

data-cars-gt_PKGFILES	= $(DATA)

data-cars-gt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


