##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 13 17:46:19 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/e-track-2

DATA      = e-track-2.xml background.png e-track-2.ac e-track-2-relief.ac e-track-2.png elevation-map.png object-map1.png object-map2.png pylon3.rgb env.png

data_PKGFILES	= $(DATA)

data_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}



