ROBOT = berniw

MODULE = ${ROBOT}.so

MODULEDIR = drivers/${ROBOT}

SOURCES   = ${ROBOT}.cpp spline.cpp trackdesc.cpp pathfinder.cpp mycar.cpp

DATADIR   = drivers/${ROBOT}

DATA      = ${ROBOT}.xml logo.rgb parameter.dat intsinsqr.dat intcossqr.dat

DATASUBDIRS = 1 2 3 4 5 6 7 8 9 10

# Mandatory Line Do Not Remove 
include ${MAKE_DEFAULT}




