##############################################################################
#
#    file                 : Makefile
#    created              : Sat Oct 30 13:07:57 CEST 1999
#    copyright            : (C) 1999 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = drivers/human/cg-gt-rwd

DATA      = skin.png skin.rgb


include ${MAKE_DEFAULT}


