##############################################################################
#
#    file        : makefile
#    created     : Tue Jul 29 19:42:26 CEST 2003
#    copyright   : (C) 2003 by Christophe Guionneau                        
#    version     : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

APROGRAM = nfs2ac

ASOURCES =  nfs2ac.cpp
ACFLAGS  += -O2

$(APROGRAM): $(ASOURCES)
	gcc $(ACFLAGS) $(ASOURCES)  -o $(APROGRAM)


include ${MAKE_DEFAULT}

