##############################################################################
#
#    file        : makefile
#    created     : Tue Jul 29 19:42:26 CEST 2003
#    copyright   : (C) 2003 by Christophe Guionneau                        
#    version     : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

PROGRAM = nfs2ac

SOURCES =  nfs2ac.cpp
CFLAGS  += -O2

$(PROGRAM): $(SOURCES)
	gcc $(CFLAGS) $(SOURCES)  -o $(PROGRAM)


