##############################################################################
#
#    file        : Makefile
#    created     : Sun Nov 10 19:52:39 CET 2002
#    copyright   : (C) 2002 by Eric Espié                        
#    email       : Eric.Espie@torcs.org   
#    version     : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

DATADIR   = cars/gt40

DATA      = gt40.xml gt40.acc \
	    tex-wheel.rgb gt40.rgb gt40-src.ac

data-cars-gt_PKGFILES	= $(DATA)

data-cars-gt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}



