##############################################################################
#
#    file                 : Makefile
#    created              : Sun May  6 15:25:23 CEST 2001
#    copyright            : (C) 2001 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR      = cars/xj-220

DATA         = xj-220.xml xj-220.rgb xj-220.ac tex-wheel.rgb


include ${MAKE_DEFAULT}


