##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 12 14:55:13 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = cars/corvette

DATA      = corvette.xml corvette-base.ac corvette.ac tex-wheel.rgb texmapper.xml corvette.rgb shadow.rgb

include ${MAKE_DEFAULT}


