##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mar 18 23:41:33 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


SOLIBRARY = libtorcs.so

SOLIBDIR  = lib

SOURCES   = entry.cpp mainmenu.cpp splash.cpp raceman.cpp exitmenu.cpp optionmenu.cpp driverconfig.cpp joystickconfig.cpp

LIBS      =  -lplibul

EXPDIR    = include

EXPORTS   = torcs.h

include ${MAKE_DEFAULT}






