#
# Tanhoj Driver
#
# @(#) $Id$
#

ROBOT = cylos1

MODULE    = ${ROBOT}.so

MODULEDIR = drivers/${ROBOT}

SOURCES   = ${ROBOT}.cpp common.cpp

DATADIR   = drivers/${ROBOT}

DATA      = ${ROBOT}.xml car1.xml cg-nascar-rwd.rgb logo.rgb

DATASUBDIRS = tracksdata

include ${MAKE_DEFAULT}


