#
# Tanhoj Driver
#
# @(#) $Id$
#

ROBOT = cylos1

SOLIBRARY = ${ROBOT}.so

SOLIBDIR  = drivers/${ROBOT}

SOURCES   = ${ROBOT}.cpp common.cpp

DATADIR   = drivers/${ROBOT}

DATA      = ${ROBOT}.xml car1.xml cg-nascar-rwd.rgb

DATASUBDIRS = tracksdata

include ${MAKE_DEFAULT}


