##############################################################################
#
#    file                 : Makefile
#    created              : Tue Feb 15 20:39:00 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/e-track-4

DATA      = e-track-4.xml background.png e-track-4.ac


include ${MAKE_DEFAULT}



