##############################################################################
#
#    file                 : Makefile<3>
#    created              : Sat Mar 18 23:55:17 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


SUBDIRS		= $(shell find * -maxdepth 0 -type d -print | grep -v CVS)

DATASUBDIRS     = $(SUBDIRS)


include ${MAKE_DEFAULT}


