##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mar 18 23:02:59 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = cars/cg-nascar-fwd

DATA      = cg-nascar-fwd.xml cg-nascar-fwd.ac cg-nascar-fwd.rgb tex-wheel.rgb

include ${MAKE_DEFAULT}


