##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 12 14:55:13 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = cars/buggy

DATA      = buggy.xml buggy.ac buggy.rgb tex-wheel.rgb buggy-src.ac

data-cars-misc_PKGFILES	= $(DATA)

data-cars-misc_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


