##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mai 20 17:12:55 CET 2006
#    copyright            : (C) 2006 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id$
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = wheel-2

DATADIR   = tracks/road/$(TRACK)

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png readme.txt background.png treeg11.png wheel.png \
			swall2.png building1.png building2.png asphalt-pit-arbor_n.png asphalt-sidel_n.png \
			tr-spec.png sbridge2.png tr-barrier-arbor-fence_n.png ggrass3.png water_green2.png \
			asphalt_n.png asphalt_mr-pitentry_n.png sign1.png sign2.png sign3.png \
			truck_arbor_ctd_n.rgb concdal.rgb treeg10.rgb tirewall.rgb truck0.rgb \
			tr-curb-bw-aa-r_n.rgb poutre3_arbor_n.rgb texwheel.rgb tree-border_n.rgb clkdtm.rgb \
			barr1_n.rgb torcs1.rgb shadow2.rgb

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


