##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 25 01:32:41 CET 2001
#    copyright            : (C) 2001 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################




DATADIR   = cars/mclaren-f1

DATA      = mclaren-f1.xml  mclaren-f1.ac \
	    mclaren-f1-lod1.ac texmapper.xml \
	    tex-wheel.rgb mclaren-f1.rgb mclaren-f1-512.rgb 

data-cars-gt_PKGFILES	= $(DATA)

data-cars-gt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}



