##############################################################################
#
#    file                 : Makefile
#    created              : Sun Apr  1 15:23:53 CEST 2001
#    copyright            : (C) 2001 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################



EXPORTS      = solid.h

EXPDIR       = include/SOLID


include ${MAKE_DEFAULT}


