##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 18 21:02:29 /etc/localtime 2001
#    copyright            : (C) 2000 by Eric Espié                        
#    email                : Eric.Espie@torcs.org   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################



DATADIR   = cars/lotus-gt1

DATA      = lotus-gt1.xml  lotus-gt1.ac \
	    lotus-gt1-base.ac texmapper.xml \
	    tex-wheel.rgb lotus-gt1.rgb lotus-gt1-512.rgb 

gt-cars_PKGFILES	= $(DATA)

gt-cars_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


