##############################################################################
#
#    file                 : Makefile<3>
#    created              : Tue Apr  4 18:25:08 CEST 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TEAM = torcs

DATADIR   = teams/${TEAM}

DATA      = ${TEAM}.xml ${TEAM}-pit.png



include ${MAKE_DEFAULT}


