##############################################################################
#
#    file                 : Makefile
#    created              : Mon Aug 30 22:10:08 CEST 1999
#    copyright            : (C) 1999 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


# #### The Open Racing Car Simulator ####


DATASUBDIRS	= drivers modules libs

EXPINCDIRS	= interfaces libs linux modules

TOOLSUBDIRS	= libs tools

SUBDIRS		= libs linux modules drivers tools

SRCDOC		= yes

include ${MAKE_DEFAULT}

