##############################################################################
#
#    file                 : Makefile
#    created              : Tue Feb 22 21:25:48 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id$                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


MODULE    = manual.so

MODULEDIR = modules/raceman/practice/control

SOURCES   = manual.cpp

include ${MAKE_DEFAULT}


